name: Tests

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # TODO Setup Postgres service
    services:
      localstack:
        image: localstack/localstack:1.3.1
        ports:
          - 4566:4566
        options: >-
          --name=localstack
          --health-cmd="curl -sS 127.0.0.1:4566 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@master
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci
